### ISSUE TITLE
Crash at Launch, java.lang.NoSuchMethodError: No static method obtainVisionFleetSkuUserToken

### ISSUE THREAD

**Issue by seemabwaqas** [mapbox/mapbox-vision-android#267]
2021-05-23 11:40:59.929 26542-26542/com.sivakumar.visionar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sivakumar.visionar, PID: 26542
    java.lang.NoSuchMethodError: No static method obtainVisionFleetSkuUserToken(Ljava/lang/String;)Ljava/lang/String; in class Lcom/mapbox/android/accounts/v1/MapboxAccounts; or its super classes (declaration of 'com.mapbox.android.accounts.v1.MapboxAccounts' appears in /data/app/~~MX9w54-oBwUWmxH_bW5jxw==/com.sivakumar.visionar-XxmXKISttmtHDHVE2ktNIg==/base.apk)
        at com.mapbox.vision.mobile.core.account.AccountManager$Impl.refreshSkuTokens(AccountManager.kt:55)
        at com.mapbox.vision.mobile.core.account.AccountManager$Impl.resetAndRescheduleToken(AccountManager.kt:38)
        at com.mapbox.vision.mobile.core.account.AccountManager$Impl.<init>(AccountManager.kt:30)
        at com.mapbox.vision.mobile.core.account.AccountManager$Impl.<init>(AccountManager.kt:17)
        at com.mapbox.vision.VisionManager.create(VisionManager.kt:241)
        at com.mapbox.vision.VisionManager.create$default(VisionManager.kt:206)
        at com.sivakumar.visionar.TutorialActivity.startVisionManager(TutorialActivity.kt:114)
        at com.sivakumar.visionar.TutorialActivity.onPermissionsGranted(TutorialActivity.kt:91)
        at com.sivakumar.visionar.BaseActivity.onCreate(BaseActivity.java:63)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-05-23 11:41:00.017 26542-26542/com.sivakumar.visionar I/Process: Sending signal. PID: 26542 SIG: 9

**Comment by seemabwaqas** [comment]
Using .aar for SDK, (gradle implementation is not working) - also adding the suggested libraries from #227 comments.

**Comment by yunikkk** [comment]
Hi @seemabwaqas , could you try an updated accounts lib, 
`com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0`  ?

**Comment by seemabwaqas** [comment]
> updated accounts lib,
> `com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0` ?

I applied, but below is the response: 
Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:7.0.0

**Comment by yunikkk** [comment]
@seemabwaqas we've just updated the docs that should fix the dependency issues, please check them at https://docs.mapbox.com/android/vision/guides/install/. Note that with the update maven is the only way to get vision dependencies now, should be much simpler that deal with the dependencies manually

**Comment by seemabwaqas** [comment]
@yunikkk I am still not able to proceed. Maven is updated already. 
Below I've added the screenshot. 

<img width="1387" alt="Screen Shot 2021-06-06 at 10 10 19 AM" src="https://user-images.githubusercontent.com/55915540/120914506-af721d80-c6af-11eb-977f-ab4cc5c130c6.png">

**Comment by yunikkk** [comment]
@seemabwaqas could you also check how the libs are added in the `dependencies` block in gradle? To me it seems you still may use downloaded libs and not maven
